In [1]:
from sklearn import datasets
digits = datasets.load_digits()


In [2]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB


dt = tree.DecisionTreeClassifier()
knn = KNeighborsClassifier(n_neighbors=3)
nb = GaussianNB()



In [3]:
from sklearn import model_selection
import numpy as np
kf = model_selection.StratifiedKFold(n_splits=10)

predicted_classes = dict()
predicted_classes['tree'] = np.zeros(digits.target.shape[0])
predicted_classes['knn'] = np.zeros(digits.target.shape[0])
predicted_classes['naiveb'] = np.zeros(digits.target.shape[0])


In [6]:
for train, test in kf.split(digits.data, digits.target):
    data_train, target_train = digits.data[train], digits.target[train]
    data_test, target_test = digits.data[test], digits.target[test]

    dt = dt.fit(data_train, target_train)
    dt_predicted = dt.predict(data_test)
    predicted_classes['tree'][test] = dt_predicted

    knn = knn.fit(data_train, target_train)
    knn_predicted = knn.predict(data_test)
    predicted_classes['knn'][test] = knn_predicted

    nb = nb.fit(data_train, target_train)
    nb_predicted = nb.predict(data_test)
    predicted_classes['naiveb'][test] = nb_predicted

In [8]:
from sklearn import metrics
for classifier in predicted_classes.keys():
    print("=======================================================================")
    print("Resultados do classificador: %s\n%s\n" 
    %(classifier, metrics.classification_report(digits.target, predicted_classes[classifier])))
    print("Matriz de confusão: \n%s\n\n\n" %metrics.confusion_matrix(digits.target, predicted_classes[classifier]))

Resultados do classificador: tree
              precision    recall  f1-score   support

           0       0.96      0.93      0.95       178
           1       0.78      0.78      0.78       182
           2       0.81      0.82      0.82       177
           3       0.81      0.79      0.80       183
           4       0.78      0.80      0.79       181
           5       0.90      0.87      0.89       182
           6       0.89      0.88      0.89       181
           7       0.83      0.82      0.82       179
           8       0.74      0.74      0.74       174
           9       0.77      0.84      0.81       180

    accuracy                           0.83      1797
   macro avg       0.83      0.83      0.83      1797
weighted avg       0.83      0.83      0.83      1797


Matriz de confusão: 
[[166   0   0   0   2   2   1   0   3   4]
 [  0 142  10   3   3   1   2   3   5  13]
 [  1   3 146   3   3   0   2   2  14   3]
 [  0   4   9 145   1   2   2   6   8   6]
 [  2  12   4