In [1]:
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection
from sklearn import metrics
from sklearn import datasets
import numpy as np

dataset = datasets.load_digits()

dt = tree.DecisionTreeClassifier()
knn = KNeighborsClassifier()
nb = GaussianNB()
mlp = MLPClassifier()
logReg = LogisticRegression()
kf = model_selection.StratifiedKFold(n_splits=10)

predicted_classes = dict()
predicted_classes['tree'] = np.zeros(dataset.target.shape[0])
predicted_classes['knn'] = np.zeros(dataset.target.shape[0])
predicted_classes['naiveb'] = np.zeros(dataset.target.shape[0])
predicted_classes['mlp'] = np.zeros(dataset.target.shape[0])
predicted_classes['logReg'] = np.zeros(dataset.target.shape[0])

In [2]:
for train, test in kf.split(dataset.data, dataset.target):
            data_train, target_train = dataset.data[train], dataset.target[train]
            data_test, target_test = dataset.data[test], dataset.target[test]

            dt = dt.fit(data_train, target_train)
            dt_predicted = dt.predict(data_test)
            predicted_classes['tree'][test] = dt_predicted

            knn = knn.fit(data_train, target_train)
            knn_predicted = knn.predict(data_test)
            predicted_classes['knn'][test] = knn_predicted

            nb = nb.fit(data_train, target_train)
            nb_predicted = nb.predict(data_test)
            predicted_classes['naiveb'][test] = nb_predicted

            mlp = mlp.fit(data_train, target_train)
            mlp_predicted = mlp.predict(data_test)
            predicted_classes['mlp'][test] = mlp_predicted

            logReg = logReg.fit(data_train, target_train)
            logReg_predicted = logReg.predict(data_test)
            predicted_classes['logReg'][test] = logReg_predicted

In [3]:
for classifier in predicted_classes.keys():
            print(
                "=======================================================================")
            print("Resultados do classificador: %s\n%s\n"
                  % (classifier, metrics.classification_report(dataset.target, predicted_classes[classifier])))
            print("Matriz de confusão: \n%s\n\n\n" % metrics.confusion_matrix(
                dataset.target, predicted_classes[classifier]))

Resultados do classificador: tree
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       178
           1       0.75      0.76      0.75       182
           2       0.80      0.80      0.80       177
           3       0.80      0.79      0.80       183
           4       0.84      0.80      0.82       181
           5       0.87      0.86      0.87       182
           6       0.87      0.87      0.87       181
           7       0.82      0.82      0.82       179
           8       0.71      0.72      0.71       174
           9       0.76      0.82      0.79       180

    accuracy                           0.82      1797
   macro avg       0.82      0.82      0.82      1797
weighted avg       0.82      0.82      0.82      1797


Matriz de confusão: 
[[165   0   2   0   4   1   1   0   1   4]
 [  0 138  11   2   4   1   7   2   6  11]
 [  1   8 142   4   0   2   2   1  14   3]
 [  0   5   8 144   0   5   1   4  10   6]
 [  2  12   2